### ISSUE TITLE
installation : Pas d'info sur le fichier `secret_key.txt`

### ISSUE THREAD

**Issue by SuliacLEGUILLOU** [Aly-ve/Alyve#1]
Bonjour.

Lors de l'installation du blog, il est fait mention d'un fichier `secret_key.txt`, mais le repo ne contient ni exemple ni information sur ce qu'il est sensé contenir.

**Comment by Aly-ve** [comment]
Bonjour @SuliacLEGUILLOU,
Le fichier `secret_key.txt` ne contient que la clé d'application unique, il faut juste créer le fichier, mettre une clé et sauvegarder.

Je mettrai une clé d'exemple dans le prochain commit. Il doit être à la racine du projet, à côté de `manage.py`.

**Comment by SuliacLEGUILLOU** [comment]
Du coup, j'ai fais une PR #2 pour gérer les quelque soucis de doc que j'ai eu durant l'installation

**Comment by Aly-ve** [comment]
Merci pour ta contribution, j'ai accepté le pull request. :+1:
